### ISSUE TITLE
The emitter not calls listeners in the order they were registered

### ISSUE THREAD

**Issue by mmillet** [Olical/EventEmitter#102]
Awesome project!
But it seems that the emitter NOT calls listeners in the order they were registered. It is opposite to the EventEmitter of Nodejs. Is the result in line with expectations?

Here is the test code:
```javascript
const EventEmitter = require('wolfy87-eventemitter');
const ee = new EventEmitter(); 
ee.on('event', () => {console.log(1)}); 
ee.on('event', () => {console.log(2)}); 
ee.on('event', () => {console.log(3)}); 
ee.emit('event'); 

// Here I go these prints:
// 3
// 2
// 1
// But in Nodejs, they would be:
// 1
// 2
// 3
```

**Comment by Olical** [comment]
Well spotted. Is this an issue though? You shouldn't be relying on the order of your events anyway, you should treat events as unordered and ignore the underlying implementation. They could be random for all we know, the same applies to the ordering of object properties when iterated over. Order should be treated as potentially random.

Anyway, the reason is here https://github.com/Olical/EventEmitter/blob/master/EventEmitter.js#L373 - I step through the events backwards because it was marginally faster back then. Maybe not now. We could change it if you really needed nodejs compatibility, but order shouldn't matter.

If order matters for you, add one listener and call all of the functions you need to execute from there.

**Comment by mmillet** [comment]
Thanks for replying. As you say, the order is really not important. In stead, I will concat listeners to one listener to ensure the order.

```javascript
const _ = require('underscore');
const EventEmitter = require('wolfy87-eventemitter');
const ee = new EventEmitter();
ee.on('event', _.compose(
  () => {console.log(3)},
  () => {console.log(2)},
  () => {console.log(1)}
));
ee.emit('event'); 
// Now I got
// 1
// 2
// 3
```

**Comment by dingfengquek** [comment]
I've once happened to use the order of event emitters in NodeJS without relying on it for my code. It was for debugging some complex chain of asynchronous functions - because of the order (nevermind that it wasn't guaranteed, it just looked like that in console.log), I could run some console.log to see the order of how the async functions were called, and solved the issue more conveniently.

Not saying that it is an issue, but when there is a choice between arbitrary/random and deterministic+easily_understood, deterministic+easily_understood is always better (even if it is negligibly better in this case). Even if it is not guaranteed.

**Comment by Olical** [comment]
I know what you mean, and I agree. Using it for debugging is great, but saying to people "please don't rely on this ordering, it may change and it's an anti-pattern" is probably a good idea.

I'm tempted to change this now, it should be relatively easy, especially with the test coverage.

This is an example of why you should *not* rely on the order though, we're talking about changing it! I would imagine a day or two after publishing I'll start getting issues about it :)

As long as it's a major version bump (which I think it should be) then we should be okay and very few people have the potential to be caught out.

**Comment by ibc** [comment]
The order of listeners execution must be the same order in which they were set. This is true for every like-EventEmitter utility I know.
