### ISSUE TITLE
TS Types are incorrect.

### ISSUE THREAD

**Issue by scotthovestadt** [Olical/EventEmitter#141]
You're not actually using an ES6 default export but the TS types you've bundled show that you are.

Here is an example of TS types that work properly:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/wolfy87-eventemitter/index.d.ts

Please fix! :)

**Comment by Olical** [comment]
Oh, thanks for reporting. The only reason I changed it was because people told me they couldn't import it but they could with the current code. I did warn that I don't use TypeScript in any way :smile:

I'd prefer to delete the file and let the DefinitelyTyped one run really. Do you think copying the DT version into here would be the best route?

**Comment by scotthovestadt** [comment]
Yeah, I would recommend just copying them into the project. Good idea :)

**Comment by Olical** [comment]
v5.2.4 should fix your issues. I copied in DefinitelyTyped's file.

**Comment by Olical** [comment]
(npm won't let me login on this machine since I enabled 2fa, so publication may be delayed...)

**Comment by Olical** [comment]
Done! (didn't realise I had nvm installed and pointing to an old version)

**Comment by scotthovestadt** [comment]
Thanks!

Just for other people's reference using TS, the right way to import this module is:
```js
import EventEmitter = require('wolfy87-eventemitter');
```
