### ISSUE TITLE
Support for Symbol data type

### ISSUE THREAD

**Issue by ollazarev** [Olical/EventEmitter#142]
In the current release, it is impossible to use, as the event name, constant with **Symbol** data type.

**Comment by Olical** [comment]
Hi there, do you mean that the library does not allow you to use `Symbol` as a name and you would like it to work?

**Comment by ollazarev** [comment]
Yes, I do.

**Comment by Olical** [comment]
Ah, okay. Is there a strong case for adding this? Like a concrete use case and problem this would solve?

I don't really work with JavaScript anymore and I'm doing the bare minimum to maintain the older projects I have out in the wild, this being one of them. I'd rather not change this project at all (other than bug fixes etc) unless I really have to. New features aren't really in my scope right now.

This would require a bunch of changes because of all the regular expression stuff I added a long time ago, which I guess I sort of regret now. That added complexity didn't really add much value, oops.

It's a nice suggestion 😄 but I don't think I can or want to add this sort of support if there isn't a very strong case for it. I have never personally used the `Symbol` type, I have no idea how I would get that support to work cleanly across all browsers.

**Comment by ollazarev** [comment]
`Symbol` type is used in ECMAScript 2015. `Symbol` type can often be used in the names of the events. So you can call the current implementation obsolete.

More about this is written in the chapter **[Symbols](https://github.com/getify/You-Dont-Know-JS/blob/master/es6%20%26%20beyond/ch2.md#symbols)** of the book "You don't know JS" by Kyle Simpson.

**Comment by Olical** [comment]
Thank you for the suggestion, but I do not want to adapt this library to support this. It adds further complexity to what should be a simple set of functions for minimal gain (in my opinion, which is subjective, of course). JavaScript engine support seems pretty patchy and this isn't preventing anyone from using this library to register and fire event listeners, which is the only objective.

You could always strip out the regular expression / string specific functionality and add support for `Symbol` in a fork? I just don't want to change this since it's been this way for 5+ years without any change.

**Comment by ollazarev** [comment]
Yes, I understand that in your case, making changes will create a lot of problems. Thank you!
