### ISSUE TITLE
How is this different than javascripts CustomEvent()

### ISSUE THREAD

**Issue by kevincam3** [Olical/EventEmitter#146]
I was just curious as to what this offers that the built in Javascript CustomEvent() object doesn't. 
I'm trying to expand my JavaScript knowledge. Thanks for any help/insight you can provide

https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent

**Comment by Olical** [comment]
CustomEvent is for bubbling events through the DOM. EventEmitter doesn't touch the DOM and is entirely self contained.

**Comment by kevincam3** [comment]
Thanks.

**Comment by thepeoplesbourgeois** [comment]
> CustomEvent is for bubbling events through the DOM.

Just curious, is that always necessarily true? It seems possible to obviate event bubbling if you instantiate a dedicated `EventTarget` to attach CustomEvents to.

```js
const dispatcher = new EventTarget();
const createUser = new CustomEvent('createUser' { ... });
dispatcher.addEventListener('createUser', function() { ... });
dispatcher.dispatchEvent(createUser);
```

Does the standard library handle this in some undesirable way? What benefits does EventEmitter provide compared to this pattern?

**Comment by Olical** [comment]
If that works for you then great! Seems a little awkward to me in some ways but I don't touch JavaScript or objects in general anymore, my point of view is skewed.

That's only possible in a browser since that's not part of a standard library, that's part of the DOM. You won't get access to that in node and you're at the mercy of browser vendors with regards to behaviour and performance (hopefully all very similar).

I'd compare performance between the two as well, I'd imagine the DOM event classes will be slower since they they have the capability to do a lot more behind the scenes, but I might be wrong. You'll just have to try it in your scenario and measure it to find out.

**Comment by thepeoplesbourgeois** [comment]
Thank you for replying. I think that in determining how fast a DOM event could theoretically be, it's important to remember that hundreds of them can occur in any given second (e.g., a `keydown`, `keyup`, and `keypress` event initialize, and go through a full event lifecycle, for every single time you press any button on your keyboard, before even considering whether or not any elements have `focus` and need to emit an `input` or `change` event). To get an idea of how many events a webpage will emit while it's open, one only needs to open a console, count how many autocomplete listings appear when you type `document.on`, and remember that all of those events are emitted, **every** time the corresponding user action is taken, and _regardless_ of what listeners exist and are waiting to handle them. If any single one of those events were appreciably slow, I doubt that the Internet would have very many people using it; therefore, DOM events must not be slow 😋

And, given how long these events have existed, I have to imagine that the subsystems in browsers for *handling* DOM events would need to also be quite well-built and fast, themselves. It's difficult to imagine a world where any successful browser would handle such a ubiquitous part of DOM interaction slowly
