### ISSUE TITLE
Eat too much memory !!!

### ISSUE THREAD

**Issue by cxwithyxy** [Olical/EventEmitter#157]
![微信截图_20210515011322](https://user-images.githubusercontent.com/3715695/118305792-0c4c3f00-b51b-11eb-94d0-5290ad4484e9.png)

#### tttt.js
```
var events = require('events');

let stmm = process.memoryUsage().heapUsed
console.log(`start memory ${stmm}`)

var eventEmitter = new events.EventEmitter();
for(let i = 0; i< 1e6; i++)
{
    eventEmitter.emit(`${Math.random()}`)
}

let endmm = process.memoryUsage().heapUsed
console.log(`end memory ${endmm}`)

console.log(`used:  ${(endmm - stmm)/1e6} M`)

```

#### chromejs.js
```
const EventEmitter = require("./EventEmitter.min.js")

let stmm = process.memoryUsage().heapUsed
console.log(`start memory ${stmm}`)

var eventEmitter = new EventEmitter();
for(let i = 0; i< 1e6; i++)
{
    eventEmitter.emit(`${Math.random()}`)
}

let endmm = process.memoryUsage().heapUsed
console.log(`end memory ${endmm}`)

console.log(`used:  ${(endmm - stmm)/1e6} M`)

```

**Comment by Olical** [comment]
Sorry, but I do not maintain this project now and it was never designed to fit the exact use cases of the node event emitter. I recommend https://github.com/primus/eventemitter3 if perf is your primary concern.

Thank you for the report and detail though, it's appreciated, I just won't be improving this library any further since I don't work with JavaScript now.
