### ISSUE TITLE
There is a  bug when use a regexp to removelisteners?

### ISSUE THREAD

**Issue by e-cloud** [Olical/EventEmitter#93]
### example:
```javascript
var ee= new EventEmitter()
ee.defineEvent('aa')
var REGEXP = /^aa$/
//...something done
ee.removeListeners(REGEXP)
output: TypeError: Cannot read property 'length' of undefined
```
https://github.com/Wolfy87/EventEmitter/blob/master/docs/api.md#removelisteners

``removeListeners``this method does many things but can't remove listeners with only a event name/regexp

**Comment by Wolfy87** [comment]
And if you use `removeListener` as opposed to `removeListeners`? It looks like it's just because there's no listeners array. I think what you're looking for is `ee.removeEvent(REGEXP)` which will remove all listeners and not require you to pass them in.

With `removeListeners` you need to provide the array of function references to be removed. I think, anyway, I wrote this quite a while ago now :D

**Comment by e-cloud** [comment]
i know ``removeEvent``, but when you use it , it will cause *another problem*--when using a **regexp** as event name, ``removeEvent ``will remove that event property which is predefined with``defineEvent``. As a result, you should call ``defineEvent`` to reregister the **regexp** event.

**Comment by e-cloud** [comment]
by the way, the original reason that i want to do that is, i have predefined some events and registered some listener on it, but i need to override the event listener. For EventEmitter which support multi-listeners, the way to do that now is only to remove , redefine and register new one.
perhaps my situation is unusual.

**Comment by Wolfy87** [comment]
It is a little unusual, but not impossible. I would not like to change `removeListener` to support removal without a function reference, that doesn't make sense. `removeEvent` *is* what you want, but it removes the knowledge of the previous event name.

Maybe a more appropriate action would be to add a "magic boolean" flag to `removeEvent` that left the name intact, something I'm not too enthusiastic about, I don't like those kind of flags and feel they should only be used in moderation.

Another solution would be to alter `removeAllListeners` so it is no longer an alias to `removeEvent`, but delegates to it then reinstates the names of the events. That method would then solve your use case (which you may have found a way around by now! Sorry!).

Thoughts on that approach? Making `removeAllListeners` a softer version of `removeEvent`.

**Comment by e-cloud** [comment]
Emmm, that is what I did that I just write some code the same as your **second solution** out of ``EventEmitter``. So, it's not reusable

**Comment by Wolfy87** [comment]
I'll see if there's a way around this some day soon. I haven't forgotten about this issue, I've just been extremely busy over the past few months with courses etc. There's probably a solution somewhere :)

**Comment by Olical** [comment]
Going to close this since I'm not going to have time to go back to it. I hope you found a way around the issue! It's just not supported by the API, it's not really a bug though (in my opinion).

If this is still a big issue for you then I can take a look, but I'm mainly just maintaining this project now instead of making the existing functions support more things. I apologise if you were still waiting on this!
