### ISSUE TITLE
Update readme to make it more clear about setOnceReturnValue stuff in v4

### ISSUE THREAD

**Issue by mitjacotic** [Olical/EventEmitter#96]
We've started with a new project and are using eventemitter because we're used to it and are using it in older projects as well (still 2.x and 3.x versions for now).
While working on this new project we got random unbinds and were hunting down a "bug" and didn't even think there could be an issue with this lib. After a while I had enough of this and started to track the trigger flow from the eventemitter itself and only then found out about the new _onceReturnValue feature which oddly/unexpectedly makes 'on' to act as 'once'.
I think it would be good to add an entry to the basic Readme.md (I know it is mentioned in the api subpage) notifying potential users upgrading the lib about this change (it can be a hard bug to find if methods which for example return true/false statuses are bound directly as handlers).

**Comment by Wolfy87** [comment]
I'm sorry to hear that, I hope it didn't slow you down for too long! I've seen someone else get bitten by this when they used it with CoffeeScript since it returns true by default with all functions.

It's just a hangover from a fairly poor design choice where I wanted my listeners array to just contain functions, not objects with meta data. I'd do it differently if I rewrote this. I was just aiming for speed initially.

I'll happy make it more obvious. That and the fact that you can't add duplicate listener references (according to the API documentation) can be confusing. I can't remember why I made it like that in the first place now.

**Comment by mitjacotic** [comment]
Wow that was fast response:)
No problem, we need such stuff to keep us sharp:) I just think that this behaviour is so unexpected that it should be more exposed. Thanks for the great lib.
